// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5KJLdA02UBmsxc6emVrnLXtqEo_9ZDn0',
    appId: '1:756811172734:web:756f40dfabb04f63ddc12f',
    messagingSenderId: '756811172734',
    projectId: 'allah-everywhere',
    authDomain: 'allah-everywhere.firebaseapp.com',
    storageBucket: 'allah-everywhere.firebasestorage.app',
    measurementId: 'G-QN92EZHPP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALJr-Z9ZpPcunzT2bp-eR8kpe3N8_1I7o',
    appId: '1:756811172734:android:627e07238874a3a0ddc12f',
    messagingSenderId: '756811172734',
    projectId: 'allah-everywhere',
    storageBucket: 'allah-everywhere.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxAEQ-1TeJPx07ZOu9v4IpXNg0r55oXnI',
    appId: '1:756811172734:ios:6cde21bc531e2831ddc12f',
    messagingSenderId: '756811172734',
    projectId: 'allah-everywhere',
    storageBucket: 'allah-everywhere.firebasestorage.app',
    iosBundleId: 'com.example.allahEverywhere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxAEQ-1TeJPx07ZOu9v4IpXNg0r55oXnI',
    appId: '1:756811172734:ios:6cde21bc531e2831ddc12f',
    messagingSenderId: '756811172734',
    projectId: 'allah-everywhere',
    storageBucket: 'allah-everywhere.firebasestorage.app',
    iosBundleId: 'com.example.allahEverywhere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5KJLdA02UBmsxc6emVrnLXtqEo_9ZDn0',
    appId: '1:756811172734:web:9368621ba94af279ddc12f',
    messagingSenderId: '756811172734',
    projectId: 'allah-everywhere',
    authDomain: 'allah-everywhere.firebaseapp.com',
    storageBucket: 'allah-everywhere.firebasestorage.app',
    measurementId: 'G-XK2VN42J2X',
  );
}
