/// UI text for the share-card studio, in each of the app's 8 languages.
/// Kept beside the feature (like the mood labels) rather than in the ARB
/// files, since it's only used here. Missing keys fall back to English.
class ShareStrings {
  final String code;

  const ShareStrings(this.code);

  String _t(String key) => _strings[code]?[key] ?? _strings['en']![key]!;

  String get title => _t('title');
  String get homeSubtitle => _t('homeSubtitle');
  String get feeling => _t('feeling');
  String get all => _t('all');
  String get quran => _t('quran');
  String get hadith => _t('hadith');
  String get story => _t('story');
  String get storyHint => _t('storyHint');
  String get post => _t('post');
  String get postHint => _t('postHint');
  String get square => _t('square');
  String get squareHint => _t('squareHint');
  String get background => _t('background');
  String get light => _t('light');
  String get dark => _t('dark');
  String get arabic => _t('arabic');
  String get translation => _t('translation');
  String get another => _t('another');
  String get share => _t('share');
  String get shareTip => _t('shareTip');
  String get shareFailed => _t('shareFailed');
  String get download => _t('download');
  String get format => _t('format');
  String get show => _t('show');
  String get divineName => _t('divineName');

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'title': 'Share a Reminder',
      'homeSubtitle': 'Turn an ayah or hadith into a status for how you feel',
      'feeling': 'How are you feeling?',
      'all': 'All',
      'quran': 'Quran',
      'hadith': 'Hadith',
      'story': 'Story',
      'storyHint': 'WhatsApp Status · Instagram Story',
      'post': 'Post',
      'postHint': 'Instagram Post',
      'square': 'Square',
      'squareHint': 'WhatsApp · Facebook',
      'background': 'Background',
      'light': 'Light',
      'dark': 'Dark',
      'arabic': 'Arabic',
      'translation': 'Translation',
      'another': 'Another',
      'share': 'Share Image',
      'shareTip': 'In the share sheet, pick WhatsApp → My Status, or Instagram → Story / Feed.',
      'shareFailed': 'Could not create the image. Please try again.',
      'download': 'Download free on Google Play & App Store',
      'format': 'Format',
      'show': 'Show',
      'divineName': 'Name of Allah',
    },
    'ar': {
      'title': 'شارك تذكرة',
      'homeSubtitle': 'حوّل آية أو حديثًا إلى حالة تناسب شعورك',
      'feeling': 'بماذا تشعر؟',
      'all': 'الكل',
      'quran': 'القرآن',
      'hadith': 'الحديث',
      'story': 'قصة',
      'storyHint': 'حالة واتساب · قصة إنستغرام',
      'post': 'منشور',
      'postHint': 'منشور إنستغرام',
      'square': 'مربع',
      'squareHint': 'واتساب · فيسبوك',
      'background': 'الخلفية',
      'light': 'فاتح',
      'dark': 'داكن',
      'arabic': 'العربية',
      'translation': 'الترجمة',
      'another': 'غيرها',
      'share': 'مشاركة الصورة',
      'shareTip': 'من قائمة المشاركة اختر واتساب ← حالتي، أو إنستغرام ← القصة / المنشور.',
      'shareFailed': 'تعذر إنشاء الصورة. حاول مرة أخرى.',
      'download': 'حمّله مجانًا من Google Play و App Store',
      'format': 'المقاس',
      'show': 'إظهار',
      'divineName': 'اسم من أسماء الله',
    },
    'ur': {
      'title': 'یاددہانی شیئر کریں',
      'homeSubtitle': 'اپنی کیفیت کے مطابق آیت یا حدیث کو اسٹیٹس بنائیں',
      'feeling': 'آپ کیسا محسوس کر رہے ہیں؟',
      'all': 'سب',
      'quran': 'قرآن',
      'hadith': 'حدیث',
      'story': 'اسٹوری',
      'storyHint': 'واٹس ایپ اسٹیٹس · انسٹاگرام اسٹوری',
      'post': 'پوسٹ',
      'postHint': 'انسٹاگرام پوسٹ',
      'square': 'مربع',
      'squareHint': 'واٹس ایپ · فیس بک',
      'background': 'پس منظر',
      'light': 'روشن',
      'dark': 'گہرا',
      'arabic': 'عربی',
      'translation': 'ترجمہ',
      'another': 'اور دکھائیں',
      'share': 'تصویر شیئر کریں',
      'shareTip': 'شیئر مینو میں واٹس ایپ ← مائی اسٹیٹس، یا انسٹاگرام ← اسٹوری / فیڈ منتخب کریں۔',
      'shareFailed': 'تصویر نہیں بن سکی۔ دوبارہ کوشش کریں۔',
      'download': 'Google Play اور App Store سے مفت ڈاؤن لوڈ کریں',
      'format': 'سائز',
      'show': 'دکھائیں',
      'divineName': 'اللہ کا نام',
    },
    'hi': {
      'title': 'याद दिलाना शेयर करें',
      'homeSubtitle': 'अपनी भावना के अनुसार आयत या हदीस को स्टेटस बनाएँ',
      'feeling': 'आप कैसा महसूस कर रहे हैं?',
      'all': 'सभी',
      'quran': 'क़ुरआन',
      'hadith': 'हदीस',
      'story': 'स्टोरी',
      'storyHint': 'WhatsApp स्टेटस · Instagram स्टोरी',
      'post': 'पोस्ट',
      'postHint': 'Instagram पोस्ट',
      'square': 'स्क्वेयर',
      'squareHint': 'WhatsApp · Facebook',
      'background': 'बैकग्राउंड',
      'light': 'लाइट',
      'dark': 'डार्क',
      'arabic': 'अरबी',
      'translation': 'अनुवाद',
      'another': 'दूसरा',
      'share': 'इमेज शेयर करें',
      'shareTip': 'शेयर मेन्यू में WhatsApp → My Status, या Instagram → Story / Feed चुनें।',
      'shareFailed': 'इमेज नहीं बन सकी। फिर से कोशिश करें।',
      'download': 'Google Play और App Store से मुफ़्त डाउनलोड करें',
      'format': 'साइज़',
      'show': 'दिखाएँ',
      'divineName': 'अल्लाह का नाम',
    },
    'zh': {
      'title': '分享提醒',
      'homeSubtitle': '根据你的心情，把经文或圣训做成状态',
      'feeling': '你现在感觉如何？',
      'all': '全部',
      'quran': '古兰经',
      'hadith': '圣训',
      'story': '快拍',
      'storyHint': 'WhatsApp 状态 · Instagram 快拍',
      'post': '帖子',
      'postHint': 'Instagram 帖子',
      'square': '方形',
      'squareHint': 'WhatsApp · Facebook',
      'background': '背景',
      'light': '浅色',
      'dark': '深色',
      'arabic': '阿拉伯文',
      'translation': '译文',
      'another': '换一个',
      'share': '分享图片',
      'shareTip': '在分享菜单中选择 WhatsApp → 我的状态，或 Instagram → 快拍 / 动态。',
      'shareFailed': '无法生成图片，请重试。',
      'download': '在 Google Play 和 App Store 免费下载',
      'format': '尺寸',
      'show': '显示',
      'divineName': '安拉的尊名',
    },
    'fr': {
      'title': 'Partager un rappel',
      'homeSubtitle': 'Transformez un verset ou un hadith en statut selon votre humeur',
      'feeling': 'Comment vous sentez-vous ?',
      'all': 'Tout',
      'quran': 'Coran',
      'hadith': 'Hadith',
      'story': 'Story',
      'storyHint': 'Statut WhatsApp · Story Instagram',
      'post': 'Publication',
      'postHint': 'Publication Instagram',
      'square': 'Carré',
      'squareHint': 'WhatsApp · Facebook',
      'background': 'Arrière-plan',
      'light': 'Clair',
      'dark': 'Sombre',
      'arabic': 'Arabe',
      'translation': 'Traduction',
      'another': 'Un autre',
      'share': 'Partager l\'image',
      'shareTip': 'Dans le menu de partage, choisissez WhatsApp → Mon statut, ou Instagram → Story / Fil.',
      'shareFailed': 'Impossible de créer l\'image. Veuillez réessayer.',
      'download': 'Téléchargez-le gratuitement sur Google Play et l\'App Store',
      'format': 'Format',
      'show': 'Afficher',
      'divineName': 'Nom d\'Allah',
    },
    'tr': {
      'title': 'Hatırlatma Paylaş',
      'homeSubtitle': 'Hissettiğine göre bir ayet ya da hadisi duruma dönüştür',
      'feeling': 'Nasıl hissediyorsun?',
      'all': 'Tümü',
      'quran': 'Kuran',
      'hadith': 'Hadis',
      'story': 'Hikaye',
      'storyHint': 'WhatsApp Durum · Instagram Hikaye',
      'post': 'Gönderi',
      'postHint': 'Instagram Gönderisi',
      'square': 'Kare',
      'squareHint': 'WhatsApp · Facebook',
      'background': 'Arka plan',
      'light': 'Açık',
      'dark': 'Koyu',
      'arabic': 'Arapça',
      'translation': 'Meal',
      'another': 'Başka',
      'share': 'Görseli Paylaş',
      'shareTip': 'Paylaşım menüsünde WhatsApp → Durumum ya da Instagram → Hikaye / Akış seçin.',
      'shareFailed': 'Görsel oluşturulamadı. Lütfen tekrar deneyin.',
      'download': 'Google Play ve App Store\'dan ücretsiz indirin',
      'format': 'Boyut',
      'show': 'Göster',
      'divineName': 'Allah\'ın İsmi',
    },
    'de': {
      'title': 'Erinnerung teilen',
      'homeSubtitle': 'Mach aus einem Vers oder Hadith einen Status, der zu deinem Gefühl passt',
      'feeling': 'Wie fühlst du dich?',
      'all': 'Alle',
      'quran': 'Koran',
      'hadith': 'Hadith',
      'story': 'Story',
      'storyHint': 'WhatsApp-Status · Instagram-Story',
      'post': 'Beitrag',
      'postHint': 'Instagram-Beitrag',
      'square': 'Quadrat',
      'squareHint': 'WhatsApp · Facebook',
      'background': 'Hintergrund',
      'light': 'Hell',
      'dark': 'Dunkel',
      'arabic': 'Arabisch',
      'translation': 'Übersetzung',
      'another': 'Noch einer',
      'share': 'Bild teilen',
      'shareTip': 'Wähle im Teilen-Menü WhatsApp → Mein Status oder Instagram → Story / Feed.',
      'shareFailed': 'Das Bild konnte nicht erstellt werden. Bitte versuche es erneut.',
      'download': 'Kostenlos bei Google Play & im App Store',
      'format': 'Format',
      'show': 'Anzeigen',
      'divineName': 'Name Allahs',
    },
  };
}
